use_frameworks!

target 'atlasdev_Example' do
  pod 'atlasdev', :path => '../'

  target 'atlasdev_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
